# Generated by Django 5.1.3 on 2024-11-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='check_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
